[tool.poetry]
name = "jungle-8-algorithm"
version = "0.1.0"
description = ""
authors = ["GoWoong <popgun10@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
